### ISSUE TITLE
The result of voc_eval_visualize is different with the result of mmdetection

### ISSUE THREAD

**Issue by liuyanzhi1214** [xiaoyu1233/mmdetection2.0_visualize#1]
The result of voc_eval_visualize is different with the result of mmdetection,it is worse than mmdetection.

**Comment by xiaoyu1233** [comment]
Which result? Could you give me an example?


| |
xiaoyu_20140901
|
|
xiaoyu_20140901@163.com
|
签名由网易邮箱大师定制
On 12/21/2020 23:01，liuyanzhi1214<notifications@github.com> wrote：

The result of voc_eval_visualize is different with the result of mmdetection,it is worse than mmdetection.

**Comment by liuyanzhi1214** [comment]
**this is the result of voc_eval_visualize.py:**
python tools/voc_eval_visualize.py ./test_result/epoch10.pkl ./work_dirs/faster_rcnn_s50_fpn_syncbn-backbone+head_mstrain-range_1x_coco/faster_rcnn_s50_fpn_syncbn-backbone+head_mstrain-range_1x_coco.py
4805 4805
/media/e706/disk_1/liuyanzhi/mmdetection-master/mmdet/core/evaluation/mean_ap_visualize.py:390: RuntimeWarning: invalid value encountered in true_divide
  f_measure = np.mean(2*(top/down))
/media/e706/disk_1/liuyanzhi/mmdetection-master/mmdet/core/evaluation/mean_ap_visualize.py:403: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.subplot(211)
/media/e706/disk_1/liuyanzhi/mmdetection-master/mmdet/core/evaluation/mean_ap_visualize.py:412: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.subplot(212)
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
2020-12-21 22:44:26,548 - print - INFO - 
+-----------+------+-------+--------+-------+
| class     | gts  | dets  | recall | ap    |
+-----------+------+-------+--------+-------+
| nail_good | 7365 | 10176 | 0.803  | 0.674 |
| nail_bad  | 2349 | 5753  | 0.609  | 0.309 |
+-----------+------+-------+--------+-------+
| mAP       |      |       |        | 0.492 |
+-----------+------+-------+--------+-------+
mAP:  0.4919012188911438
**this is the result of mmdetection:**
 python tools/test.py work_dirs/faster_rcnn_s50_fpn_syncbn-backbone+head_mstrain-range_1x_coco/faster_rcnn_s50_fpn_syncbn-backbone+head_mstrain-range_1x_coco.py work_dirs/faster_rcnn_s50_fpn_syncbn-backbone+head_mstrain-range_1x_coco/epoch_10.pth --eval mAP
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4805/4805, 10.7 task/s, elapsed: 451s, ETA:     0s
+-----------+------+------+--------+-------+
| class     | gts  | dets | recall | ap    |
+-----------+------+------+--------+-------+
| nail_good | 7365 | 9990 | 0.967  | 0.873 |
| nail_bad  | 2349 | 5180 | 0.932  | 0.839 |
+-----------+------+------+--------+-------+
| mAP       |      |      |        | 0.856 |
+-----------+------+------+--------+-------+
OrderedDict([('mAP', 0.8556843996047974)])
